### PR TITLE
Extra and traits

### PR DESCRIPTION
**Pull request by not-my-profile**
If you like these changes please merge them without squashing.

### CODE REVIEW

**Comment by elliottslaughter** [comment]
Thanks, will try to look at this in the next couple of days.

**Comment by not-my-profile** [comment]
Thanks, if you have any questions, just ask :)

**Comment by elliottslaughter** [comment]
@not-my-profile I see the stringify test, but are the iterators tested?

I don't suppose there's any way to make sure the documentation code samples are checked to at least compile?

**Comment by not-my-profile** [comment]
Yes, I didn't write tests for the iterators other than the stringify test.

`cargo test` automatically tests the documentation code samples (not just that they compile but also their assertions).

**Comment by elliottslaughter** [comment]
Do you want to test the iterators? It's mostly simple code, though there are a few places (like the tables) where it seems a bit more nontrivial.

Otherwise are done with this PR on your end?

**Comment by not-my-profile** [comment]
I added tests for the mutable iterators (including the mutable table iterators). While this still doesn't test some immutable iterators their code is identical to the mutable iterators so it should be fine.

While the tests work locally for me they apparently fail in the GitHub CI because of:

```diff
716c716
> [NOBODY@NOWHERE.NET](mailto:nobody@nowhere.net){.email}
---
< [NOBODY\@NOWHERE.NET](mailto:nobody@nowhere.net){.email}
```

which is apparently caused by a change in the Pandoc Markdown writer (I generated `tests/testsuite_uppercase.txt` locally with pandoc 2.17.0.1).

I see a couple of solutions:

* we could just remove the `@` from both `testsuite.txt` and `testsuite_uppercase.txt`
* we could update the Pandoc version used in the CI
  https://github.com/elliottslaughter/rust-pandoc-types/blob/34e7a90c5a5e5d4523d13d03ab69ceb9b8cea2bf/.github/workflows/test.yml#L32
* we could avoid the last json -> markdown roundtrip and change the uppercase fixtures to JSON (but that would make the tests less readable imo)

Please tell me what you prefer.

> Otherwise are done with this PR on your end?

There are a couple of more changes that I think would be beneficial but I don't know if you want them:

* Changing the `Pandoc` struct from a tuple to a C struct.
* Introducing a struct for `Table`, I find tuple variants with so many fields to be unwieldy. This would also let use box the table struct in the `Block` enum (which Clippy suggests since there is large size difference between variants). Plus the `Table` struct could derive `Default` which would make constructing tables more comfortable.

**Comment by elliottslaughter** [comment]
Let's upgrade the Pandoc version.

I'm ok with making those types into structs.

**Comment by not-my-profile** [comment]
Ok I think I'm done on my end.

**Comment by elliottslaughter** [comment]
Thanks again for working on this. Let me know if there's anything else you want to get into a 0.5 release.

**Comment by not-my-profile** [comment]
Thanks! I don't have any other changes in mind.

**Comment by elliottslaughter** [comment]
This has now been released as 0.5.0. Thanks again!

**Pull request merged**
